// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/admin': {
    params: {};
  };
  '/admin/claims': {
    params: {};
  };
  '/admin/documents/:id': {
    params: {
      id: string;
    };
  };
  '/admin/documents': {
    params: {};
  };
  '/admin/email-domains/:id': {
    params: {
      id: string;
    };
  };
  '/admin/email-domains': {
    params: {};
  };
  '/admin/organisation-insights/:id': {
    params: {
      id: string;
    };
  };
  '/admin/organisation-insights': {
    params: {};
  };
  '/admin/organisation-stats': {
    params: {};
  };
  '/admin/organisations/:id': {
    params: {
      id: string;
    };
  };
  '/admin/organisations': {
    params: {};
  };
  '/admin/site-settings': {
    params: {};
  };
  '/admin/stats': {
    params: {};
  };
  '/admin/teams/:id': {
    params: {
      id: string;
    };
  };
  '/admin/unsealed-documents': {
    params: {};
  };
  '/admin/users/:id': {
    params: {
      id: string;
    };
  };
  '/admin/users': {
    params: {};
  };
  '/dashboard': {
    params: {};
  };
  '/inbox': {
    params: {};
  };
  '/o/:orgUrl': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/billing': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/branding': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/document': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/email-domains/:id': {
    params: {
      orgUrl: string;
      id: string;
    };
  };
  '/o/:orgUrl/settings/email-domains': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/email': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/general': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/groups/:id': {
    params: {
      orgUrl: string;
      id: string;
    };
  };
  '/o/:orgUrl/settings/groups': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/members': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/sso': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/settings/teams': {
    params: {
      orgUrl: string;
    };
  };
  '/o/:orgUrl/support': {
    params: {
      orgUrl: string;
    };
  };
  '/settings': {
    params: {};
  };
  '/settings/billing-personal': {
    params: {};
  };
  '/settings/branding': {
    params: {};
  };
  '/settings/document': {
    params: {};
  };
  '/settings/email': {
    params: {};
  };
  '/settings/public-profile': {
    params: {};
  };
  '/settings/tokens': {
    params: {};
  };
  '/settings/webhooks/:id': {
    params: {
      id: string;
    };
  };
  '/settings/webhooks': {
    params: {};
  };
  '/settings/billing': {
    params: {};
  };
  '/settings/organisations': {
    params: {};
  };
  '/settings/profile': {
    params: {};
  };
  '/settings/security': {
    params: {};
  };
  '/settings/security/activity': {
    params: {};
  };
  '/settings/security/linked-accounts': {
    params: {};
  };
  '/settings/security/passkeys': {
    params: {};
  };
  '/settings/security/sessions': {
    params: {};
  };
  '/t/:teamUrl': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/documents/:id': {
    params: {
      teamUrl: string;
      id: string;
    };
  };
  '/t/:teamUrl/documents/:id/edit': {
    params: {
      teamUrl: string;
      id: string;
    };
  };
  '/t/:teamUrl/documents/:id/legacy_editor': {
    params: {
      teamUrl: string;
      id: string;
    };
  };
  '/t/:teamUrl/documents/:id/logs': {
    params: {
      teamUrl: string;
      id: string;
    };
  };
  '/t/:teamUrl/documents': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/documents/f/:folderId': {
    params: {
      teamUrl: string;
      folderId: string;
    };
  };
  '/t/:teamUrl/documents/folders': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/settings': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/settings/branding': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/settings/document': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/settings/email': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/settings/groups': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/settings/members': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/settings/public-profile': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/settings/tokens': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/settings/webhooks/:id': {
    params: {
      teamUrl: string;
      id: string;
    };
  };
  '/t/:teamUrl/settings/webhooks': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/templates/:id': {
    params: {
      teamUrl: string;
      id: string;
    };
  };
  '/t/:teamUrl/templates/:id/edit': {
    params: {
      teamUrl: string;
      id: string;
    };
  };
  '/t/:teamUrl/templates/:id/legacy_editor': {
    params: {
      teamUrl: string;
      id: string;
    };
  };
  '/t/:teamUrl/templates': {
    params: {
      teamUrl: string;
    };
  };
  '/t/:teamUrl/templates/f/:folderId': {
    params: {
      teamUrl: string;
      folderId: string;
    };
  };
  '/t/:teamUrl/templates/folders': {
    params: {
      teamUrl: string;
    };
  };
  '/__htmltopdf/audit-log': {
    params: {};
  };
  '/__htmltopdf/certificate': {
    params: {};
  };
  '/p/:url': {
    params: {
      url: string;
    };
  };
  '/d/:token': {
    params: {
      token: string;
    };
  };
  '/sign/:token': {
    params: {
      token: string;
    };
  };
  '/sign/:token/complete': {
    params: {
      token: string;
    };
  };
  '/sign/:token/expired': {
    params: {
      token: string;
    };
  };
  '/sign/:token/rejected': {
    params: {
      token: string;
    };
  };
  '/sign/:token/waiting': {
    params: {
      token: string;
    };
  };
  '/ingest/*': {
    params: {
      '*': string;
    };
  };
  '/share/:slug': {
    params: {
      slug: string;
    };
  };
  '/share/:slug/opengraph': {
    params: {
      slug: string;
    };
  };
  '/articles/signature-disclosure': {
    params: {};
  };
  '/check-email': {
    params: {};
  };
  '/forgot-password': {
    params: {};
  };
  '/o/:orgUrl/signin': {
    params: {
      orgUrl: string;
    };
  };
  '/organisation/decline/:token': {
    params: {
      token: string;
    };
  };
  '/organisation/invite/:token': {
    params: {
      token: string;
    };
  };
  '/organisation/sso/confirmation/:token': {
    params: {
      token: string;
    };
  };
  '/reset-password/:token': {
    params: {
      token: string;
    };
  };
  '/reset-password': {
    params: {};
  };
  '/signin': {
    params: {};
  };
  '/signup': {
    params: {};
  };
  '/team/verify/email/:token': {
    params: {
      token: string;
    };
  };
  '/unverified-account': {
    params: {};
  };
  '/verify-email/:token': {
    params: {
      token: string;
    };
  };
  '/verify-email': {
    params: {};
  };
  '/api/avatar/:id': {
    params: {
      id: string;
    };
  };
  '/api/branding/logo/organisation/:orgId': {
    params: {
      orgId: string;
    };
  };
  '/api/branding/logo/team/:teamId': {
    params: {
      teamId: string;
    };
  };
  '/api/certificate-status': {
    params: {};
  };
  '/api/health': {
    params: {};
  };
  '/api/limits': {
    params: {};
  };
  '/api/locale': {
    params: {};
  };
  '/api/stripe/webhook': {
    params: {};
  };
  '/api/theme': {
    params: {};
  };
  '/api/webhook/trigger': {
    params: {};
  };
  '/embed': {
    params: {};
  };
  '/embed/direct/:token': {
    params: {
      token: string;
    };
  };
  '/embed/sign/:token': {
    params: {
      token: string;
    };
  };
  '/embed/playground': {
    params: {};
  };
  '/embed/v1/authoring': {
    params: {};
  };
  '/embed/v1/authoring/document/create': {
    params: {};
  };
  '/embed/v1/authoring/document/edit/:id': {
    params: {
      id: string;
    };
  };
  '/embed/v1/authoring/template/create': {
    params: {};
  };
  '/embed/v1/authoring/template/edit/:id': {
    params: {
      id: string;
    };
  };
  '/embed/v1/authoring/completed/create': {
    params: {};
  };
  '/embed/v1/multisign': {
    params: {};
  };
  '/embed/v2/authoring': {
    params: {};
  };
  '/embed/v2/authoring/envelope/create': {
    params: {};
  };
  '/embed/v2/authoring/envelope/edit/:id': {
    params: {
      id: string;
    };
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page:
      | '/'
      | '/admin'
      | '/admin/claims'
      | '/admin/documents/:id'
      | '/admin/documents'
      | '/admin/email-domains/:id'
      | '/admin/email-domains'
      | '/admin/organisation-insights/:id'
      | '/admin/organisation-insights'
      | '/admin/organisation-stats'
      | '/admin/organisations/:id'
      | '/admin/organisations'
      | '/admin/site-settings'
      | '/admin/stats'
      | '/admin/teams/:id'
      | '/admin/unsealed-documents'
      | '/admin/users/:id'
      | '/admin/users'
      | '/dashboard'
      | '/inbox'
      | '/o/:orgUrl'
      | '/o/:orgUrl/settings'
      | '/o/:orgUrl/settings/billing'
      | '/o/:orgUrl/settings/branding'
      | '/o/:orgUrl/settings/document'
      | '/o/:orgUrl/settings/email-domains/:id'
      | '/o/:orgUrl/settings/email-domains'
      | '/o/:orgUrl/settings/email'
      | '/o/:orgUrl/settings/general'
      | '/o/:orgUrl/settings/groups/:id'
      | '/o/:orgUrl/settings/groups'
      | '/o/:orgUrl/settings/members'
      | '/o/:orgUrl/settings/sso'
      | '/o/:orgUrl/settings/teams'
      | '/o/:orgUrl/support'
      | '/settings'
      | '/settings/billing-personal'
      | '/settings/branding'
      | '/settings/document'
      | '/settings/email'
      | '/settings/public-profile'
      | '/settings/tokens'
      | '/settings/webhooks/:id'
      | '/settings/webhooks'
      | '/settings/billing'
      | '/settings/organisations'
      | '/settings/profile'
      | '/settings/security'
      | '/settings/security/activity'
      | '/settings/security/linked-accounts'
      | '/settings/security/passkeys'
      | '/settings/security/sessions'
      | '/t/:teamUrl'
      | '/t/:teamUrl/documents/:id'
      | '/t/:teamUrl/documents/:id/edit'
      | '/t/:teamUrl/documents/:id/legacy_editor'
      | '/t/:teamUrl/documents/:id/logs'
      | '/t/:teamUrl/documents'
      | '/t/:teamUrl/documents/f/:folderId'
      | '/t/:teamUrl/documents/folders'
      | '/t/:teamUrl/settings'
      | '/t/:teamUrl/settings/branding'
      | '/t/:teamUrl/settings/document'
      | '/t/:teamUrl/settings/email'
      | '/t/:teamUrl/settings/groups'
      | '/t/:teamUrl/settings/members'
      | '/t/:teamUrl/settings/public-profile'
      | '/t/:teamUrl/settings/tokens'
      | '/t/:teamUrl/settings/webhooks/:id'
      | '/t/:teamUrl/settings/webhooks'
      | '/t/:teamUrl/templates/:id'
      | '/t/:teamUrl/templates/:id/edit'
      | '/t/:teamUrl/templates/:id/legacy_editor'
      | '/t/:teamUrl/templates'
      | '/t/:teamUrl/templates/f/:folderId'
      | '/t/:teamUrl/templates/folders'
      | '/__htmltopdf/audit-log'
      | '/__htmltopdf/certificate'
      | '/p/:url'
      | '/d/:token'
      | '/sign/:token'
      | '/sign/:token/complete'
      | '/sign/:token/expired'
      | '/sign/:token/rejected'
      | '/sign/:token/waiting'
      | '/ingest/*'
      | '/share/:slug'
      | '/share/:slug/opengraph'
      | '/articles/signature-disclosure'
      | '/check-email'
      | '/forgot-password'
      | '/o/:orgUrl/signin'
      | '/organisation/decline/:token'
      | '/organisation/invite/:token'
      | '/organisation/sso/confirmation/:token'
      | '/reset-password/:token'
      | '/reset-password'
      | '/signin'
      | '/signup'
      | '/team/verify/email/:token'
      | '/unverified-account'
      | '/verify-email/:token'
      | '/verify-email'
      | '/api/avatar/:id'
      | '/api/branding/logo/organisation/:orgId'
      | '/api/branding/logo/team/:teamId'
      | '/api/certificate-status'
      | '/api/health'
      | '/api/limits'
      | '/api/locale'
      | '/api/stripe/webhook'
      | '/api/theme'
      | '/api/webhook/trigger'
      | '/embed'
      | '/embed/direct/:token'
      | '/embed/sign/:token'
      | '/embed/playground'
      | '/embed/v1/authoring'
      | '/embed/v1/authoring/document/create'
      | '/embed/v1/authoring/document/edit/:id'
      | '/embed/v1/authoring/template/create'
      | '/embed/v1/authoring/template/edit/:id'
      | '/embed/v1/authoring/completed/create'
      | '/embed/v1/multisign'
      | '/embed/v2/authoring'
      | '/embed/v2/authoring/envelope/create'
      | '/embed/v2/authoring/envelope/edit/:id';
  };
  'routes/_authenticated+/_layout.tsx': {
    id: 'routes/_authenticated+/_layout';
    page:
      | '/admin'
      | '/admin/claims'
      | '/admin/documents/:id'
      | '/admin/documents'
      | '/admin/email-domains/:id'
      | '/admin/email-domains'
      | '/admin/organisation-insights/:id'
      | '/admin/organisation-insights'
      | '/admin/organisation-stats'
      | '/admin/organisations/:id'
      | '/admin/organisations'
      | '/admin/site-settings'
      | '/admin/stats'
      | '/admin/teams/:id'
      | '/admin/unsealed-documents'
      | '/admin/users/:id'
      | '/admin/users'
      | '/dashboard'
      | '/inbox'
      | '/o/:orgUrl'
      | '/o/:orgUrl/settings'
      | '/o/:orgUrl/settings/billing'
      | '/o/:orgUrl/settings/branding'
      | '/o/:orgUrl/settings/document'
      | '/o/:orgUrl/settings/email-domains/:id'
      | '/o/:orgUrl/settings/email-domains'
      | '/o/:orgUrl/settings/email'
      | '/o/:orgUrl/settings/general'
      | '/o/:orgUrl/settings/groups/:id'
      | '/o/:orgUrl/settings/groups'
      | '/o/:orgUrl/settings/members'
      | '/o/:orgUrl/settings/sso'
      | '/o/:orgUrl/settings/teams'
      | '/o/:orgUrl/support'
      | '/settings'
      | '/settings/billing-personal'
      | '/settings/branding'
      | '/settings/document'
      | '/settings/email'
      | '/settings/public-profile'
      | '/settings/tokens'
      | '/settings/webhooks/:id'
      | '/settings/webhooks'
      | '/settings/billing'
      | '/settings/organisations'
      | '/settings/profile'
      | '/settings/security'
      | '/settings/security/activity'
      | '/settings/security/linked-accounts'
      | '/settings/security/passkeys'
      | '/settings/security/sessions'
      | '/t/:teamUrl'
      | '/t/:teamUrl/documents/:id'
      | '/t/:teamUrl/documents/:id/edit'
      | '/t/:teamUrl/documents/:id/legacy_editor'
      | '/t/:teamUrl/documents/:id/logs'
      | '/t/:teamUrl/documents'
      | '/t/:teamUrl/documents/f/:folderId'
      | '/t/:teamUrl/documents/folders'
      | '/t/:teamUrl/settings'
      | '/t/:teamUrl/settings/branding'
      | '/t/:teamUrl/settings/document'
      | '/t/:teamUrl/settings/email'
      | '/t/:teamUrl/settings/groups'
      | '/t/:teamUrl/settings/members'
      | '/t/:teamUrl/settings/public-profile'
      | '/t/:teamUrl/settings/tokens'
      | '/t/:teamUrl/settings/webhooks/:id'
      | '/t/:teamUrl/settings/webhooks'
      | '/t/:teamUrl/templates/:id'
      | '/t/:teamUrl/templates/:id/edit'
      | '/t/:teamUrl/templates/:id/legacy_editor'
      | '/t/:teamUrl/templates'
      | '/t/:teamUrl/templates/f/:folderId'
      | '/t/:teamUrl/templates/folders';
  };
  'routes/_authenticated+/admin+/_layout.tsx': {
    id: 'routes/_authenticated+/admin+/_layout';
    page:
      | '/admin'
      | '/admin/claims'
      | '/admin/documents/:id'
      | '/admin/documents'
      | '/admin/email-domains/:id'
      | '/admin/email-domains'
      | '/admin/organisation-insights/:id'
      | '/admin/organisation-insights'
      | '/admin/organisation-stats'
      | '/admin/organisations/:id'
      | '/admin/organisations'
      | '/admin/site-settings'
      | '/admin/stats'
      | '/admin/teams/:id'
      | '/admin/unsealed-documents'
      | '/admin/users/:id'
      | '/admin/users';
  };
  'routes/_authenticated+/admin+/_index.tsx': {
    id: 'routes/_authenticated+/admin+/_index';
    page: '/admin';
  };
  'routes/_authenticated+/admin+/claims.tsx': {
    id: 'routes/_authenticated+/admin+/claims';
    page: '/admin/claims';
  };
  'routes/_authenticated+/admin+/documents.$id.tsx': {
    id: 'routes/_authenticated+/admin+/documents.$id';
    page: '/admin/documents/:id';
  };
  'routes/_authenticated+/admin+/documents._index.tsx': {
    id: 'routes/_authenticated+/admin+/documents._index';
    page: '/admin/documents';
  };
  'routes/_authenticated+/admin+/email-domains.$id.tsx': {
    id: 'routes/_authenticated+/admin+/email-domains.$id';
    page: '/admin/email-domains/:id';
  };
  'routes/_authenticated+/admin+/email-domains._index.tsx': {
    id: 'routes/_authenticated+/admin+/email-domains._index';
    page: '/admin/email-domains';
  };
  'routes/_authenticated+/admin+/organisation-insights.$id.tsx': {
    id: 'routes/_authenticated+/admin+/organisation-insights.$id';
    page: '/admin/organisation-insights/:id';
  };
  'routes/_authenticated+/admin+/organisation-insights._index.tsx': {
    id: 'routes/_authenticated+/admin+/organisation-insights._index';
    page: '/admin/organisation-insights';
  };
  'routes/_authenticated+/admin+/organisation-stats._index.tsx': {
    id: 'routes/_authenticated+/admin+/organisation-stats._index';
    page: '/admin/organisation-stats';
  };
  'routes/_authenticated+/admin+/organisations.$id.tsx': {
    id: 'routes/_authenticated+/admin+/organisations.$id';
    page: '/admin/organisations/:id';
  };
  'routes/_authenticated+/admin+/organisations._index.tsx': {
    id: 'routes/_authenticated+/admin+/organisations._index';
    page: '/admin/organisations';
  };
  'routes/_authenticated+/admin+/site-settings.tsx': {
    id: 'routes/_authenticated+/admin+/site-settings';
    page: '/admin/site-settings';
  };
  'routes/_authenticated+/admin+/stats.tsx': {
    id: 'routes/_authenticated+/admin+/stats';
    page: '/admin/stats';
  };
  'routes/_authenticated+/admin+/teams.$id.tsx': {
    id: 'routes/_authenticated+/admin+/teams.$id';
    page: '/admin/teams/:id';
  };
  'routes/_authenticated+/admin+/unsealed-documents._index.tsx': {
    id: 'routes/_authenticated+/admin+/unsealed-documents._index';
    page: '/admin/unsealed-documents';
  };
  'routes/_authenticated+/admin+/users.$id.tsx': {
    id: 'routes/_authenticated+/admin+/users.$id';
    page: '/admin/users/:id';
  };
  'routes/_authenticated+/admin+/users._index.tsx': {
    id: 'routes/_authenticated+/admin+/users._index';
    page: '/admin/users';
  };
  'routes/_authenticated+/dashboard.tsx': {
    id: 'routes/_authenticated+/dashboard';
    page: '/dashboard';
  };
  'routes/_authenticated+/inbox.tsx': {
    id: 'routes/_authenticated+/inbox';
    page: '/inbox';
  };
  'routes/_authenticated+/o.$orgUrl._layout.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl._layout';
    page:
      | '/o/:orgUrl'
      | '/o/:orgUrl/settings'
      | '/o/:orgUrl/settings/billing'
      | '/o/:orgUrl/settings/branding'
      | '/o/:orgUrl/settings/document'
      | '/o/:orgUrl/settings/email-domains/:id'
      | '/o/:orgUrl/settings/email-domains'
      | '/o/:orgUrl/settings/email'
      | '/o/:orgUrl/settings/general'
      | '/o/:orgUrl/settings/groups/:id'
      | '/o/:orgUrl/settings/groups'
      | '/o/:orgUrl/settings/members'
      | '/o/:orgUrl/settings/sso'
      | '/o/:orgUrl/settings/teams'
      | '/o/:orgUrl/support';
  };
  'routes/_authenticated+/o.$orgUrl._index.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl._index';
    page: '/o/:orgUrl';
  };
  'routes/_authenticated+/o.$orgUrl.settings._layout.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings._layout';
    page:
      | '/o/:orgUrl/settings'
      | '/o/:orgUrl/settings/billing'
      | '/o/:orgUrl/settings/branding'
      | '/o/:orgUrl/settings/document'
      | '/o/:orgUrl/settings/email-domains/:id'
      | '/o/:orgUrl/settings/email-domains'
      | '/o/:orgUrl/settings/email'
      | '/o/:orgUrl/settings/general'
      | '/o/:orgUrl/settings/groups/:id'
      | '/o/:orgUrl/settings/groups'
      | '/o/:orgUrl/settings/members'
      | '/o/:orgUrl/settings/sso'
      | '/o/:orgUrl/settings/teams';
  };
  'routes/_authenticated+/o.$orgUrl.settings._index.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings._index';
    page: '/o/:orgUrl/settings';
  };
  'routes/_authenticated+/o.$orgUrl.settings.billing.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.billing';
    page: '/o/:orgUrl/settings/billing';
  };
  'routes/_authenticated+/o.$orgUrl.settings.branding.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.branding';
    page: '/o/:orgUrl/settings/branding';
  };
  'routes/_authenticated+/o.$orgUrl.settings.document.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.document';
    page: '/o/:orgUrl/settings/document';
  };
  'routes/_authenticated+/o.$orgUrl.settings.email-domains.$id.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.email-domains.$id';
    page: '/o/:orgUrl/settings/email-domains/:id';
  };
  'routes/_authenticated+/o.$orgUrl.settings.email-domains._index.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.email-domains._index';
    page: '/o/:orgUrl/settings/email-domains';
  };
  'routes/_authenticated+/o.$orgUrl.settings.email.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.email';
    page: '/o/:orgUrl/settings/email';
  };
  'routes/_authenticated+/o.$orgUrl.settings.general.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.general';
    page: '/o/:orgUrl/settings/general';
  };
  'routes/_authenticated+/o.$orgUrl.settings.groups.$id.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.groups.$id';
    page: '/o/:orgUrl/settings/groups/:id';
  };
  'routes/_authenticated+/o.$orgUrl.settings.groups._index.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.groups._index';
    page: '/o/:orgUrl/settings/groups';
  };
  'routes/_authenticated+/o.$orgUrl.settings.members.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.members';
    page: '/o/:orgUrl/settings/members';
  };
  'routes/_authenticated+/o.$orgUrl.settings.sso.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.sso';
    page: '/o/:orgUrl/settings/sso';
  };
  'routes/_authenticated+/o.$orgUrl.settings.teams.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.settings.teams';
    page: '/o/:orgUrl/settings/teams';
  };
  'routes/_authenticated+/o.$orgUrl.support.tsx': {
    id: 'routes/_authenticated+/o.$orgUrl.support';
    page: '/o/:orgUrl/support';
  };
  'routes/_authenticated+/settings+/_layout.tsx': {
    id: 'routes/_authenticated+/settings+/_layout';
    page:
      | '/settings'
      | '/settings/billing-personal'
      | '/settings/branding'
      | '/settings/document'
      | '/settings/email'
      | '/settings/public-profile'
      | '/settings/tokens'
      | '/settings/webhooks/:id'
      | '/settings/webhooks'
      | '/settings/billing'
      | '/settings/organisations'
      | '/settings/profile'
      | '/settings/security'
      | '/settings/security/activity'
      | '/settings/security/linked-accounts'
      | '/settings/security/passkeys'
      | '/settings/security/sessions';
  };
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/_layout.tsx': {
    id: 'routes/_authenticated+/settings+/_dynamic_personal_routes+/_layout';
    page:
      | '/settings/billing-personal'
      | '/settings/branding'
      | '/settings/document'
      | '/settings/email'
      | '/settings/public-profile'
      | '/settings/tokens'
      | '/settings/webhooks/:id'
      | '/settings/webhooks';
  };
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/billing-personal.tsx': {
    id: 'routes/_authenticated+/settings+/_dynamic_personal_routes+/billing-personal';
    page: '/settings/billing-personal';
  };
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/branding.tsx': {
    id: 'routes/_authenticated+/settings+/_dynamic_personal_routes+/branding';
    page: '/settings/branding';
  };
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/document.tsx': {
    id: 'routes/_authenticated+/settings+/_dynamic_personal_routes+/document';
    page: '/settings/document';
  };
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/email.tsx': {
    id: 'routes/_authenticated+/settings+/_dynamic_personal_routes+/email';
    page: '/settings/email';
  };
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/public-profile.tsx': {
    id: 'routes/_authenticated+/settings+/_dynamic_personal_routes+/public-profile';
    page: '/settings/public-profile';
  };
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/tokens.tsx': {
    id: 'routes/_authenticated+/settings+/_dynamic_personal_routes+/tokens';
    page: '/settings/tokens';
  };
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/webhooks.$id._index.tsx': {
    id: 'routes/_authenticated+/settings+/_dynamic_personal_routes+/webhooks.$id._index';
    page: '/settings/webhooks/:id';
  };
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/webhooks._index.tsx': {
    id: 'routes/_authenticated+/settings+/_dynamic_personal_routes+/webhooks._index';
    page: '/settings/webhooks';
  };
  'routes/_authenticated+/settings+/_index.tsx': {
    id: 'routes/_authenticated+/settings+/_index';
    page: '/settings';
  };
  'routes/_authenticated+/settings+/billing.tsx': {
    id: 'routes/_authenticated+/settings+/billing';
    page: '/settings/billing';
  };
  'routes/_authenticated+/settings+/organisations.tsx': {
    id: 'routes/_authenticated+/settings+/organisations';
    page: '/settings/organisations';
  };
  'routes/_authenticated+/settings+/profile.tsx': {
    id: 'routes/_authenticated+/settings+/profile';
    page: '/settings/profile';
  };
  'routes/_authenticated+/settings+/security._index.tsx': {
    id: 'routes/_authenticated+/settings+/security._index';
    page: '/settings/security';
  };
  'routes/_authenticated+/settings+/security.activity.tsx': {
    id: 'routes/_authenticated+/settings+/security.activity';
    page: '/settings/security/activity';
  };
  'routes/_authenticated+/settings+/security.linked-accounts.tsx': {
    id: 'routes/_authenticated+/settings+/security.linked-accounts';
    page: '/settings/security/linked-accounts';
  };
  'routes/_authenticated+/settings+/security.passkeys.tsx': {
    id: 'routes/_authenticated+/settings+/security.passkeys';
    page: '/settings/security/passkeys';
  };
  'routes/_authenticated+/settings+/security.sessions.tsx': {
    id: 'routes/_authenticated+/settings+/security.sessions';
    page: '/settings/security/sessions';
  };
  'routes/_authenticated+/t.$teamUrl+/_layout.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/_layout';
    page:
      | '/t/:teamUrl'
      | '/t/:teamUrl/documents/:id'
      | '/t/:teamUrl/documents/:id/edit'
      | '/t/:teamUrl/documents/:id/legacy_editor'
      | '/t/:teamUrl/documents/:id/logs'
      | '/t/:teamUrl/documents'
      | '/t/:teamUrl/documents/f/:folderId'
      | '/t/:teamUrl/documents/folders'
      | '/t/:teamUrl/settings'
      | '/t/:teamUrl/settings/branding'
      | '/t/:teamUrl/settings/document'
      | '/t/:teamUrl/settings/email'
      | '/t/:teamUrl/settings/groups'
      | '/t/:teamUrl/settings/members'
      | '/t/:teamUrl/settings/public-profile'
      | '/t/:teamUrl/settings/tokens'
      | '/t/:teamUrl/settings/webhooks/:id'
      | '/t/:teamUrl/settings/webhooks'
      | '/t/:teamUrl/templates/:id'
      | '/t/:teamUrl/templates/:id/edit'
      | '/t/:teamUrl/templates/:id/legacy_editor'
      | '/t/:teamUrl/templates'
      | '/t/:teamUrl/templates/f/:folderId'
      | '/t/:teamUrl/templates/folders';
  };
  'routes/_authenticated+/t.$teamUrl+/_index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/_index';
    page: '/t/:teamUrl';
  };
  'routes/_authenticated+/t.$teamUrl+/documents.$id._layout.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/documents.$id._layout';
    page:
      | '/t/:teamUrl/documents/:id'
      | '/t/:teamUrl/documents/:id/edit'
      | '/t/:teamUrl/documents/:id/legacy_editor'
      | '/t/:teamUrl/documents/:id/logs';
  };
  'routes/_authenticated+/t.$teamUrl+/documents.$id._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/documents.$id._index';
    page: '/t/:teamUrl/documents/:id';
  };
  'routes/_authenticated+/t.$teamUrl+/documents.$id.edit.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/documents.$id.edit';
    page: '/t/:teamUrl/documents/:id/edit';
  };
  'routes/_authenticated+/t.$teamUrl+/documents.$id.legacy_editor.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/documents.$id.legacy_editor';
    page: '/t/:teamUrl/documents/:id/legacy_editor';
  };
  'routes/_authenticated+/t.$teamUrl+/documents.$id.logs.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/documents.$id.logs';
    page: '/t/:teamUrl/documents/:id/logs';
  };
  'routes/_authenticated+/t.$teamUrl+/documents._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/documents._index';
    page: '/t/:teamUrl/documents';
  };
  'routes/_authenticated+/t.$teamUrl+/documents.f.$folderId._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/documents.f.$folderId._index';
    page: '/t/:teamUrl/documents/f/:folderId';
  };
  'routes/_authenticated+/t.$teamUrl+/documents.folders._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/documents.folders._index';
    page: '/t/:teamUrl/documents/folders';
  };
  'routes/_authenticated+/t.$teamUrl+/settings._layout.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings._layout';
    page:
      | '/t/:teamUrl/settings'
      | '/t/:teamUrl/settings/branding'
      | '/t/:teamUrl/settings/document'
      | '/t/:teamUrl/settings/email'
      | '/t/:teamUrl/settings/groups'
      | '/t/:teamUrl/settings/members'
      | '/t/:teamUrl/settings/public-profile'
      | '/t/:teamUrl/settings/tokens'
      | '/t/:teamUrl/settings/webhooks/:id'
      | '/t/:teamUrl/settings/webhooks';
  };
  'routes/_authenticated+/t.$teamUrl+/settings._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings._index';
    page: '/t/:teamUrl/settings';
  };
  'routes/_authenticated+/t.$teamUrl+/settings.branding.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings.branding';
    page: '/t/:teamUrl/settings/branding';
  };
  'routes/_authenticated+/t.$teamUrl+/settings.document.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings.document';
    page: '/t/:teamUrl/settings/document';
  };
  'routes/_authenticated+/t.$teamUrl+/settings.email.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings.email';
    page: '/t/:teamUrl/settings/email';
  };
  'routes/_authenticated+/t.$teamUrl+/settings.groups.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings.groups';
    page: '/t/:teamUrl/settings/groups';
  };
  'routes/_authenticated+/t.$teamUrl+/settings.members.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings.members';
    page: '/t/:teamUrl/settings/members';
  };
  'routes/_authenticated+/t.$teamUrl+/settings.public-profile.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings.public-profile';
    page: '/t/:teamUrl/settings/public-profile';
  };
  'routes/_authenticated+/t.$teamUrl+/settings.tokens.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings.tokens';
    page: '/t/:teamUrl/settings/tokens';
  };
  'routes/_authenticated+/t.$teamUrl+/settings.webhooks.$id._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings.webhooks.$id._index';
    page: '/t/:teamUrl/settings/webhooks/:id';
  };
  'routes/_authenticated+/t.$teamUrl+/settings.webhooks._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/settings.webhooks._index';
    page: '/t/:teamUrl/settings/webhooks';
  };
  'routes/_authenticated+/t.$teamUrl+/templates.$id._layout.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/templates.$id._layout';
    page: '/t/:teamUrl/templates/:id' | '/t/:teamUrl/templates/:id/edit' | '/t/:teamUrl/templates/:id/legacy_editor';
  };
  'routes/_authenticated+/t.$teamUrl+/templates.$id._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/templates.$id._index';
    page: '/t/:teamUrl/templates/:id';
  };
  'routes/_authenticated+/t.$teamUrl+/templates.$id.edit.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/templates.$id.edit';
    page: '/t/:teamUrl/templates/:id/edit';
  };
  'routes/_authenticated+/t.$teamUrl+/templates.$id.legacy_editor.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/templates.$id.legacy_editor';
    page: '/t/:teamUrl/templates/:id/legacy_editor';
  };
  'routes/_authenticated+/t.$teamUrl+/templates._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/templates._index';
    page: '/t/:teamUrl/templates';
  };
  'routes/_authenticated+/t.$teamUrl+/templates.f.$folderId._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/templates.f.$folderId._index';
    page: '/t/:teamUrl/templates/f/:folderId';
  };
  'routes/_authenticated+/t.$teamUrl+/templates.folders._index.tsx': {
    id: 'routes/_authenticated+/t.$teamUrl+/templates.folders._index';
    page: '/t/:teamUrl/templates/folders';
  };
  'routes/_index.tsx': {
    id: 'routes/_index';
    page: '/';
  };
  'routes/_internal+/[__htmltopdf]+/audit-log.tsx': {
    id: 'routes/_internal+/[__htmltopdf]+/audit-log';
    page: '/__htmltopdf/audit-log';
  };
  'routes/_internal+/[__htmltopdf]+/certificate.tsx': {
    id: 'routes/_internal+/[__htmltopdf]+/certificate';
    page: '/__htmltopdf/certificate';
  };
  'routes/_profile+/_layout.tsx': {
    id: 'routes/_profile+/_layout';
    page: '/p/:url';
  };
  'routes/_profile+/p.$url.tsx': {
    id: 'routes/_profile+/p.$url';
    page: '/p/:url';
  };
  'routes/_recipient+/_layout.tsx': {
    id: 'routes/_recipient+/_layout';
    page:
      | '/d/:token'
      | '/sign/:token'
      | '/sign/:token/complete'
      | '/sign/:token/expired'
      | '/sign/:token/rejected'
      | '/sign/:token/waiting';
  };
  'routes/_recipient+/d.$token+/_index.tsx': {
    id: 'routes/_recipient+/d.$token+/_index';
    page: '/d/:token';
  };
  'routes/_recipient+/sign.$token+/_index.tsx': {
    id: 'routes/_recipient+/sign.$token+/_index';
    page: '/sign/:token';
  };
  'routes/_recipient+/sign.$token+/complete.tsx': {
    id: 'routes/_recipient+/sign.$token+/complete';
    page: '/sign/:token/complete';
  };
  'routes/_recipient+/sign.$token+/expired.tsx': {
    id: 'routes/_recipient+/sign.$token+/expired';
    page: '/sign/:token/expired';
  };
  'routes/_recipient+/sign.$token+/rejected.tsx': {
    id: 'routes/_recipient+/sign.$token+/rejected';
    page: '/sign/:token/rejected';
  };
  'routes/_recipient+/sign.$token+/waiting.tsx': {
    id: 'routes/_recipient+/sign.$token+/waiting';
    page: '/sign/:token/waiting';
  };
  'routes/_redirects+/ingest.$.tsx': {
    id: 'routes/_redirects+/ingest.$';
    page: '/ingest/*';
  };
  'routes/_share+/_layout.tsx': {
    id: 'routes/_share+/_layout';
    page: '/share/:slug' | '/share/:slug/opengraph';
  };
  'routes/_share+/share.$slug.tsx': {
    id: 'routes/_share+/share.$slug';
    page: '/share/:slug' | '/share/:slug/opengraph';
  };
  'routes/_share+/share.$slug.opengraph.tsx': {
    id: 'routes/_share+/share.$slug.opengraph';
    page: '/share/:slug/opengraph';
  };
  'routes/_unauthenticated+/_layout.tsx': {
    id: 'routes/_unauthenticated+/_layout';
    page:
      | '/articles/signature-disclosure'
      | '/check-email'
      | '/forgot-password'
      | '/o/:orgUrl/signin'
      | '/organisation/decline/:token'
      | '/organisation/invite/:token'
      | '/organisation/sso/confirmation/:token'
      | '/reset-password/:token'
      | '/reset-password'
      | '/signin'
      | '/signup'
      | '/team/verify/email/:token'
      | '/unverified-account'
      | '/verify-email/:token'
      | '/verify-email';
  };
  'routes/_unauthenticated+/articles.signature-disclosure.tsx': {
    id: 'routes/_unauthenticated+/articles.signature-disclosure';
    page: '/articles/signature-disclosure';
  };
  'routes/_unauthenticated+/check-email.tsx': {
    id: 'routes/_unauthenticated+/check-email';
    page: '/check-email';
  };
  'routes/_unauthenticated+/forgot-password.tsx': {
    id: 'routes/_unauthenticated+/forgot-password';
    page: '/forgot-password';
  };
  'routes/_unauthenticated+/o.$orgUrl.signin.tsx': {
    id: 'routes/_unauthenticated+/o.$orgUrl.signin';
    page: '/o/:orgUrl/signin';
  };
  'routes/_unauthenticated+/organisation.decline.$token.tsx': {
    id: 'routes/_unauthenticated+/organisation.decline.$token';
    page: '/organisation/decline/:token';
  };
  'routes/_unauthenticated+/organisation.invite.$token.tsx': {
    id: 'routes/_unauthenticated+/organisation.invite.$token';
    page: '/organisation/invite/:token';
  };
  'routes/_unauthenticated+/organisation.sso.confirmation.$token.tsx': {
    id: 'routes/_unauthenticated+/organisation.sso.confirmation.$token';
    page: '/organisation/sso/confirmation/:token';
  };
  'routes/_unauthenticated+/reset-password.$token.tsx': {
    id: 'routes/_unauthenticated+/reset-password.$token';
    page: '/reset-password/:token';
  };
  'routes/_unauthenticated+/reset-password._index.tsx': {
    id: 'routes/_unauthenticated+/reset-password._index';
    page: '/reset-password';
  };
  'routes/_unauthenticated+/signin.tsx': {
    id: 'routes/_unauthenticated+/signin';
    page: '/signin';
  };
  'routes/_unauthenticated+/signup.tsx': {
    id: 'routes/_unauthenticated+/signup';
    page: '/signup';
  };
  'routes/_unauthenticated+/team.verify.email.$token.tsx': {
    id: 'routes/_unauthenticated+/team.verify.email.$token';
    page: '/team/verify/email/:token';
  };
  'routes/_unauthenticated+/unverified-account.tsx': {
    id: 'routes/_unauthenticated+/unverified-account';
    page: '/unverified-account';
  };
  'routes/_unauthenticated+/verify-email.$token.tsx': {
    id: 'routes/_unauthenticated+/verify-email.$token';
    page: '/verify-email/:token';
  };
  'routes/_unauthenticated+/verify-email._index.tsx': {
    id: 'routes/_unauthenticated+/verify-email._index';
    page: '/verify-email';
  };
  'routes/api+/avatar.$id.tsx': {
    id: 'routes/api+/avatar.$id';
    page: '/api/avatar/:id';
  };
  'routes/api+/branding.logo.organisation.$orgId.ts': {
    id: 'routes/api+/branding.logo.organisation.$orgId';
    page: '/api/branding/logo/organisation/:orgId';
  };
  'routes/api+/branding.logo.team.$teamId.ts': {
    id: 'routes/api+/branding.logo.team.$teamId';
    page: '/api/branding/logo/team/:teamId';
  };
  'routes/api+/certificate-status.ts': {
    id: 'routes/api+/certificate-status';
    page: '/api/certificate-status';
  };
  'routes/api+/health.ts': {
    id: 'routes/api+/health';
    page: '/api/health';
  };
  'routes/api+/limits.tsx': {
    id: 'routes/api+/limits';
    page: '/api/limits';
  };
  'routes/api+/locale.tsx': {
    id: 'routes/api+/locale';
    page: '/api/locale';
  };
  'routes/api+/stripe.webhook.ts': {
    id: 'routes/api+/stripe.webhook';
    page: '/api/stripe/webhook';
  };
  'routes/api+/theme.tsx': {
    id: 'routes/api+/theme';
    page: '/api/theme';
  };
  'routes/api+/webhook.trigger.ts': {
    id: 'routes/api+/webhook.trigger';
    page: '/api/webhook/trigger';
  };
  'routes/embed+/_v0+/_layout.tsx': {
    id: 'routes/embed+/_v0+/_layout';
    page: '/embed' | '/embed/direct/:token' | '/embed/sign/:token';
  };
  'routes/embed+/_v0+/direct.$token.tsx': {
    id: 'routes/embed+/_v0+/direct.$token';
    page: '/embed/direct/:token';
  };
  'routes/embed+/_v0+/sign.$token.tsx': {
    id: 'routes/embed+/_v0+/sign.$token';
    page: '/embed/sign/:token';
  };
  'routes/embed+/playground.tsx': {
    id: 'routes/embed+/playground';
    page: '/embed/playground';
  };
  'routes/embed+/v1+/authoring+/_layout.tsx': {
    id: 'routes/embed+/v1+/authoring+/_layout';
    page:
      | '/embed/v1/authoring'
      | '/embed/v1/authoring/document/create'
      | '/embed/v1/authoring/document/edit/:id'
      | '/embed/v1/authoring/template/create'
      | '/embed/v1/authoring/template/edit/:id';
  };
  'routes/embed+/v1+/authoring+/document.create.tsx': {
    id: 'routes/embed+/v1+/authoring+/document.create';
    page: '/embed/v1/authoring/document/create';
  };
  'routes/embed+/v1+/authoring+/document.edit.$id.tsx': {
    id: 'routes/embed+/v1+/authoring+/document.edit.$id';
    page: '/embed/v1/authoring/document/edit/:id';
  };
  'routes/embed+/v1+/authoring+/template.create.tsx': {
    id: 'routes/embed+/v1+/authoring+/template.create';
    page: '/embed/v1/authoring/template/create';
  };
  'routes/embed+/v1+/authoring+/template.edit.$id.tsx': {
    id: 'routes/embed+/v1+/authoring+/template.edit.$id';
    page: '/embed/v1/authoring/template/edit/:id';
  };
  'routes/embed+/v1+/authoring_.completed.create.tsx': {
    id: 'routes/embed+/v1+/authoring_.completed.create';
    page: '/embed/v1/authoring/completed/create';
  };
  'routes/embed+/v1+/multisign+/_index.tsx': {
    id: 'routes/embed+/v1+/multisign+/_index';
    page: '/embed/v1/multisign';
  };
  'routes/embed+/v2+/authoring+/_layout.tsx': {
    id: 'routes/embed+/v2+/authoring+/_layout';
    page: '/embed/v2/authoring' | '/embed/v2/authoring/envelope/create' | '/embed/v2/authoring/envelope/edit/:id';
  };
  'routes/embed+/v2+/authoring+/envelope.create._index.tsx': {
    id: 'routes/embed+/v2+/authoring+/envelope.create._index';
    page: '/embed/v2/authoring/envelope/create';
  };
  'routes/embed+/v2+/authoring+/envelope.edit.$id.tsx': {
    id: 'routes/embed+/v2+/authoring+/envelope.edit.$id';
    page: '/embed/v2/authoring/envelope/edit/:id';
  };
};

type RouteModules = {
  root: typeof import('./app/root.tsx');
  'routes/_authenticated+/_layout': typeof import('./app/routes/_authenticated+/_layout.tsx');
  'routes/_authenticated+/admin+/_layout': typeof import('./app/routes/_authenticated+/admin+/_layout.tsx');
  'routes/_authenticated+/admin+/_index': typeof import('./app/routes/_authenticated+/admin+/_index.tsx');
  'routes/_authenticated+/admin+/claims': typeof import('./app/routes/_authenticated+/admin+/claims.tsx');
  'routes/_authenticated+/admin+/documents.$id': typeof import('./app/routes/_authenticated+/admin+/documents.$id.tsx');
  'routes/_authenticated+/admin+/documents._index': typeof import('./app/routes/_authenticated+/admin+/documents._index.tsx');
  'routes/_authenticated+/admin+/email-domains.$id': typeof import('./app/routes/_authenticated+/admin+/email-domains.$id.tsx');
  'routes/_authenticated+/admin+/email-domains._index': typeof import('./app/routes/_authenticated+/admin+/email-domains._index.tsx');
  'routes/_authenticated+/admin+/organisation-insights.$id': typeof import('./app/routes/_authenticated+/admin+/organisation-insights.$id.tsx');
  'routes/_authenticated+/admin+/organisation-insights._index': typeof import('./app/routes/_authenticated+/admin+/organisation-insights._index.tsx');
  'routes/_authenticated+/admin+/organisation-stats._index': typeof import('./app/routes/_authenticated+/admin+/organisation-stats._index.tsx');
  'routes/_authenticated+/admin+/organisations.$id': typeof import('./app/routes/_authenticated+/admin+/organisations.$id.tsx');
  'routes/_authenticated+/admin+/organisations._index': typeof import('./app/routes/_authenticated+/admin+/organisations._index.tsx');
  'routes/_authenticated+/admin+/site-settings': typeof import('./app/routes/_authenticated+/admin+/site-settings.tsx');
  'routes/_authenticated+/admin+/stats': typeof import('./app/routes/_authenticated+/admin+/stats.tsx');
  'routes/_authenticated+/admin+/teams.$id': typeof import('./app/routes/_authenticated+/admin+/teams.$id.tsx');
  'routes/_authenticated+/admin+/unsealed-documents._index': typeof import('./app/routes/_authenticated+/admin+/unsealed-documents._index.tsx');
  'routes/_authenticated+/admin+/users.$id': typeof import('./app/routes/_authenticated+/admin+/users.$id.tsx');
  'routes/_authenticated+/admin+/users._index': typeof import('./app/routes/_authenticated+/admin+/users._index.tsx');
  'routes/_authenticated+/dashboard': typeof import('./app/routes/_authenticated+/dashboard.tsx');
  'routes/_authenticated+/inbox': typeof import('./app/routes/_authenticated+/inbox.tsx');
  'routes/_authenticated+/o.$orgUrl._layout': typeof import('./app/routes/_authenticated+/o.$orgUrl._layout.tsx');
  'routes/_authenticated+/o.$orgUrl._index': typeof import('./app/routes/_authenticated+/o.$orgUrl._index.tsx');
  'routes/_authenticated+/o.$orgUrl.settings._layout': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings._layout.tsx');
  'routes/_authenticated+/o.$orgUrl.settings._index': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings._index.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.billing': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.billing.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.branding': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.branding.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.document': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.document.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.email-domains.$id': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.email-domains.$id.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.email-domains._index': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.email-domains._index.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.email': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.email.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.general': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.general.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.groups.$id': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.groups.$id.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.groups._index': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.groups._index.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.members': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.members.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.sso': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.sso.tsx');
  'routes/_authenticated+/o.$orgUrl.settings.teams': typeof import('./app/routes/_authenticated+/o.$orgUrl.settings.teams.tsx');
  'routes/_authenticated+/o.$orgUrl.support': typeof import('./app/routes/_authenticated+/o.$orgUrl.support.tsx');
  'routes/_authenticated+/settings+/_layout': typeof import('./app/routes/_authenticated+/settings+/_layout.tsx');
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/_layout': typeof import('./app/routes/_authenticated+/settings+/_dynamic_personal_routes+/_layout.tsx');
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/billing-personal': typeof import('./app/routes/_authenticated+/settings+/_dynamic_personal_routes+/billing-personal.tsx');
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/branding': typeof import('./app/routes/_authenticated+/settings+/_dynamic_personal_routes+/branding.tsx');
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/document': typeof import('./app/routes/_authenticated+/settings+/_dynamic_personal_routes+/document.tsx');
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/email': typeof import('./app/routes/_authenticated+/settings+/_dynamic_personal_routes+/email.tsx');
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/public-profile': typeof import('./app/routes/_authenticated+/settings+/_dynamic_personal_routes+/public-profile.tsx');
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/tokens': typeof import('./app/routes/_authenticated+/settings+/_dynamic_personal_routes+/tokens.tsx');
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/webhooks.$id._index': typeof import('./app/routes/_authenticated+/settings+/_dynamic_personal_routes+/webhooks.$id._index.tsx');
  'routes/_authenticated+/settings+/_dynamic_personal_routes+/webhooks._index': typeof import('./app/routes/_authenticated+/settings+/_dynamic_personal_routes+/webhooks._index.tsx');
  'routes/_authenticated+/settings+/_index': typeof import('./app/routes/_authenticated+/settings+/_index.tsx');
  'routes/_authenticated+/settings+/billing': typeof import('./app/routes/_authenticated+/settings+/billing.tsx');
  'routes/_authenticated+/settings+/organisations': typeof import('./app/routes/_authenticated+/settings+/organisations.tsx');
  'routes/_authenticated+/settings+/profile': typeof import('./app/routes/_authenticated+/settings+/profile.tsx');
  'routes/_authenticated+/settings+/security._index': typeof import('./app/routes/_authenticated+/settings+/security._index.tsx');
  'routes/_authenticated+/settings+/security.activity': typeof import('./app/routes/_authenticated+/settings+/security.activity.tsx');
  'routes/_authenticated+/settings+/security.linked-accounts': typeof import('./app/routes/_authenticated+/settings+/security.linked-accounts.tsx');
  'routes/_authenticated+/settings+/security.passkeys': typeof import('./app/routes/_authenticated+/settings+/security.passkeys.tsx');
  'routes/_authenticated+/settings+/security.sessions': typeof import('./app/routes/_authenticated+/settings+/security.sessions.tsx');
  'routes/_authenticated+/t.$teamUrl+/_layout': typeof import('./app/routes/_authenticated+/t.$teamUrl+/_layout.tsx');
  'routes/_authenticated+/t.$teamUrl+/_index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/_index.tsx');
  'routes/_authenticated+/t.$teamUrl+/documents.$id._layout': typeof import('./app/routes/_authenticated+/t.$teamUrl+/documents.$id._layout.tsx');
  'routes/_authenticated+/t.$teamUrl+/documents.$id._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/documents.$id._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/documents.$id.edit': typeof import('./app/routes/_authenticated+/t.$teamUrl+/documents.$id.edit.tsx');
  'routes/_authenticated+/t.$teamUrl+/documents.$id.legacy_editor': typeof import('./app/routes/_authenticated+/t.$teamUrl+/documents.$id.legacy_editor.tsx');
  'routes/_authenticated+/t.$teamUrl+/documents.$id.logs': typeof import('./app/routes/_authenticated+/t.$teamUrl+/documents.$id.logs.tsx');
  'routes/_authenticated+/t.$teamUrl+/documents._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/documents._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/documents.f.$folderId._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/documents.f.$folderId._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/documents.folders._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/documents.folders._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings._layout': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings._layout.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings.branding': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings.branding.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings.document': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings.document.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings.email': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings.email.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings.groups': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings.groups.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings.members': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings.members.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings.public-profile': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings.public-profile.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings.tokens': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings.tokens.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings.webhooks.$id._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings.webhooks.$id._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/settings.webhooks._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/settings.webhooks._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/templates.$id._layout': typeof import('./app/routes/_authenticated+/t.$teamUrl+/templates.$id._layout.tsx');
  'routes/_authenticated+/t.$teamUrl+/templates.$id._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/templates.$id._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/templates.$id.edit': typeof import('./app/routes/_authenticated+/t.$teamUrl+/templates.$id.edit.tsx');
  'routes/_authenticated+/t.$teamUrl+/templates.$id.legacy_editor': typeof import('./app/routes/_authenticated+/t.$teamUrl+/templates.$id.legacy_editor.tsx');
  'routes/_authenticated+/t.$teamUrl+/templates._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/templates._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/templates.f.$folderId._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/templates.f.$folderId._index.tsx');
  'routes/_authenticated+/t.$teamUrl+/templates.folders._index': typeof import('./app/routes/_authenticated+/t.$teamUrl+/templates.folders._index.tsx');
  'routes/_index': typeof import('./app/routes/_index.tsx');
  'routes/_internal+/[__htmltopdf]+/audit-log': typeof import('./app/routes/_internal+/[__htmltopdf]+/audit-log.tsx');
  'routes/_internal+/[__htmltopdf]+/certificate': typeof import('./app/routes/_internal+/[__htmltopdf]+/certificate.tsx');
  'routes/_profile+/_layout': typeof import('./app/routes/_profile+/_layout.tsx');
  'routes/_profile+/p.$url': typeof import('./app/routes/_profile+/p.$url.tsx');
  'routes/_recipient+/_layout': typeof import('./app/routes/_recipient+/_layout.tsx');
  'routes/_recipient+/d.$token+/_index': typeof import('./app/routes/_recipient+/d.$token+/_index.tsx');
  'routes/_recipient+/sign.$token+/_index': typeof import('./app/routes/_recipient+/sign.$token+/_index.tsx');
  'routes/_recipient+/sign.$token+/complete': typeof import('./app/routes/_recipient+/sign.$token+/complete.tsx');
  'routes/_recipient+/sign.$token+/expired': typeof import('./app/routes/_recipient+/sign.$token+/expired.tsx');
  'routes/_recipient+/sign.$token+/rejected': typeof import('./app/routes/_recipient+/sign.$token+/rejected.tsx');
  'routes/_recipient+/sign.$token+/waiting': typeof import('./app/routes/_recipient+/sign.$token+/waiting.tsx');
  'routes/_redirects+/ingest.$': typeof import('./app/routes/_redirects+/ingest.$.tsx');
  'routes/_share+/_layout': typeof import('./app/routes/_share+/_layout.tsx');
  'routes/_share+/share.$slug': typeof import('./app/routes/_share+/share.$slug.tsx');
  'routes/_share+/share.$slug.opengraph': typeof import('./app/routes/_share+/share.$slug.opengraph.tsx');
  'routes/_unauthenticated+/_layout': typeof import('./app/routes/_unauthenticated+/_layout.tsx');
  'routes/_unauthenticated+/articles.signature-disclosure': typeof import('./app/routes/_unauthenticated+/articles.signature-disclosure.tsx');
  'routes/_unauthenticated+/check-email': typeof import('./app/routes/_unauthenticated+/check-email.tsx');
  'routes/_unauthenticated+/forgot-password': typeof import('./app/routes/_unauthenticated+/forgot-password.tsx');
  'routes/_unauthenticated+/o.$orgUrl.signin': typeof import('./app/routes/_unauthenticated+/o.$orgUrl.signin.tsx');
  'routes/_unauthenticated+/organisation.decline.$token': typeof import('./app/routes/_unauthenticated+/organisation.decline.$token.tsx');
  'routes/_unauthenticated+/organisation.invite.$token': typeof import('./app/routes/_unauthenticated+/organisation.invite.$token.tsx');
  'routes/_unauthenticated+/organisation.sso.confirmation.$token': typeof import('./app/routes/_unauthenticated+/organisation.sso.confirmation.$token.tsx');
  'routes/_unauthenticated+/reset-password.$token': typeof import('./app/routes/_unauthenticated+/reset-password.$token.tsx');
  'routes/_unauthenticated+/reset-password._index': typeof import('./app/routes/_unauthenticated+/reset-password._index.tsx');
  'routes/_unauthenticated+/signin': typeof import('./app/routes/_unauthenticated+/signin.tsx');
  'routes/_unauthenticated+/signup': typeof import('./app/routes/_unauthenticated+/signup.tsx');
  'routes/_unauthenticated+/team.verify.email.$token': typeof import('./app/routes/_unauthenticated+/team.verify.email.$token.tsx');
  'routes/_unauthenticated+/unverified-account': typeof import('./app/routes/_unauthenticated+/unverified-account.tsx');
  'routes/_unauthenticated+/verify-email.$token': typeof import('./app/routes/_unauthenticated+/verify-email.$token.tsx');
  'routes/_unauthenticated+/verify-email._index': typeof import('./app/routes/_unauthenticated+/verify-email._index.tsx');
  'routes/api+/avatar.$id': typeof import('./app/routes/api+/avatar.$id.tsx');
  'routes/api+/branding.logo.organisation.$orgId': typeof import('./app/routes/api+/branding.logo.organisation.$orgId.ts');
  'routes/api+/branding.logo.team.$teamId': typeof import('./app/routes/api+/branding.logo.team.$teamId.ts');
  'routes/api+/certificate-status': typeof import('./app/routes/api+/certificate-status.ts');
  'routes/api+/health': typeof import('./app/routes/api+/health.ts');
  'routes/api+/limits': typeof import('./app/routes/api+/limits.tsx');
  'routes/api+/locale': typeof import('./app/routes/api+/locale.tsx');
  'routes/api+/stripe.webhook': typeof import('./app/routes/api+/stripe.webhook.ts');
  'routes/api+/theme': typeof import('./app/routes/api+/theme.tsx');
  'routes/api+/webhook.trigger': typeof import('./app/routes/api+/webhook.trigger.ts');
  'routes/embed+/_v0+/_layout': typeof import('./app/routes/embed+/_v0+/_layout.tsx');
  'routes/embed+/_v0+/direct.$token': typeof import('./app/routes/embed+/_v0+/direct.$token.tsx');
  'routes/embed+/_v0+/sign.$token': typeof import('./app/routes/embed+/_v0+/sign.$token.tsx');
  'routes/embed+/playground': typeof import('./app/routes/embed+/playground.tsx');
  'routes/embed+/v1+/authoring+/_layout': typeof import('./app/routes/embed+/v1+/authoring+/_layout.tsx');
  'routes/embed+/v1+/authoring+/document.create': typeof import('./app/routes/embed+/v1+/authoring+/document.create.tsx');
  'routes/embed+/v1+/authoring+/document.edit.$id': typeof import('./app/routes/embed+/v1+/authoring+/document.edit.$id.tsx');
  'routes/embed+/v1+/authoring+/template.create': typeof import('./app/routes/embed+/v1+/authoring+/template.create.tsx');
  'routes/embed+/v1+/authoring+/template.edit.$id': typeof import('./app/routes/embed+/v1+/authoring+/template.edit.$id.tsx');
  'routes/embed+/v1+/authoring_.completed.create': typeof import('./app/routes/embed+/v1+/authoring_.completed.create.tsx');
  'routes/embed+/v1+/multisign+/_index': typeof import('./app/routes/embed+/v1+/multisign+/_index.tsx');
  'routes/embed+/v2+/authoring+/_layout': typeof import('./app/routes/embed+/v2+/authoring+/_layout.tsx');
  'routes/embed+/v2+/authoring+/envelope.create._index': typeof import('./app/routes/embed+/v2+/authoring+/envelope.create._index.tsx');
  'routes/embed+/v2+/authoring+/envelope.edit.$id': typeof import('./app/routes/embed+/v2+/authoring+/envelope.edit.$id.tsx');
};
